# Generated by Django 2.2.19 on 2022-02-08 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinfavorite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Тот, кто добавил в избранное', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoriter', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AddField(
            model_name='recipeincart',
            name='recipe',
            field=models.ForeignKey(blank=True, help_text='Рецепт в корзину покупок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_in_cart', to='app.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='recipeincart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Тот, кто добавил в корзину', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_follower', to=settings.AUTH_USER_MODEL, verbose_name='Пользоватеть'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='app.IngredientInRecipe', to='app.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='app.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Recipe', verbose_name='Рецепт'),
        ),
    ]
