# Generated by Django 2.2.19 on 2022-02-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220212_1359'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.CheckConstraint(check=models.Q(amount__gt=0), name='amount_gt_0'),
        ),
    ]
