# Generated by Django 2.2.19 on 2021-11-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211126_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Связь "Ингридиент - Рецепт"', 'verbose_name_plural': 'Связи "Ингридиент - Рецепт"'},
        ),
    ]
