# Generated by Django 2.2.19 on 2021-11-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211126_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientInRecipe',
        ),
    ]
