# Generated by Django 2.2.19 on 2022-02-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220212_1522'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='amount_gt_0',
        ),
    ]
