# Generated by Django 2.2.19 on 2022-02-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220212_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': 'Связь "Ингредиент - Рецепт"', 'verbose_name_plural': 'Связи "Ингредиент - Рецепт"'},
        ),
    ]
