# Generated by Django 2.2.19 on 2022-02-02 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20211126_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(blank=True, help_text='Избранный рецепт', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoriting', to='app.Recipe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(blank=True, help_text='Тот, кто добавил в избранное', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoriter', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
