# Generated by Django 2.2.19 on 2022-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_recipeincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Изображение'),
        ),
    ]
